DROP TABLE User;
DROP TABLE Song;
DROP TABLE Playlist;
DROP TABLE Listens;
DROP TABLE Saves;
DROP TABLE Follows;


CREATE TABLE User(username VARCHAR(20) NOT NULL PRIMARY KEY, password VARCHAR(20) NOT NULL,email VARCHAR(20) NOT NULL);
CREATE TABLE Song(name VARCHAR(20) NOT NULL PRIMARY KEY,artist VARCHAR(20) NOT NULL,genre VARCHAR(20) NOT NULL);
CREATE TABLE Playlist(name VARCHAR(20) NOT NULL PRIMARY KEY,song INTEGER NOT NULL REFERENCES Song(name),private BOOLEAN NOT NULL);
CREATE TABLE Listens(user VARCHAR(20) NOT NULL REFERENCES User(username),song VARCHAR(20) NOT NULL REFERENCES Song(name),count INTEGER NOT NULL,PRIMARY KEY(user, song));
CREATE TABLE Saves(user VARCHAR(20) NOT NULL REFERENCES User(username),playlist VARCHAR(20) NOT NULL REFERENCES Playlist(name),PRIMARY KEY(user, playlist));
CREATE TABLE Follows(user1 VARCHAR(20) NOT NULL REFERENCES User(username),user2 VARCHAR(20) NOT NULL REFERENCES User(username),PRIMARY KEY(user1, user2));
